version: "3"

name: "gvd_practica_final"

services:
  spark:
    container_name: "practica-final-spark-master"
    image: docker.io/bitnami/spark:3.2.4
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    ports:
      - "8080:8080"
    user: root
    volumes:
      - type: bind
        source: code
        target: /opt/bitnami/spark/code
        bind:
          create_host_path: true
      - type: bind
        source: dataset
        target: /opt/bitnami/spark/dataset
        bind:
          create_host_path: true
      - type: bind
        source: setup.sh
        target: /opt/bitnami/spark/setup.sh
        bind:
          create_host_path: true
      - type: bind
        source: requirements.txt
        target: /opt/bitnami/spark/requirements.txt
        bind:
          create_host_path: true
    command:
      - sh
      - -c
      - |
        echo 'Iniciando configuración...'
        ./setup.sh
        echo 'Configuración realizada'
        tail -f /dev/null
    networks:
      - proxynet

  spark-worker:
    container_name: "practica-final-spark-worker"
    image: docker.io/bitnami/spark:3.2.4
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    networks:
      - proxynet

  mongo:
    container_name: "practica-final-mongo"
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27018:27017
    networks:
      - proxynet

  mongo-express:
    container_name: "practica-final-mongo-express"
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    networks:
      - proxynet

  jupyter:
    container_name: "practica-final-jupyter"
    image: jupyter/pyspark-notebook:spark-3.2.1
    restart: always
    ports:
      - 8888:8888
    networks:
      - proxynet
    volumes:
      - ./:/home/jovyan
    command: ["start-notebook.sh", "--NotebookApp.token", "''"]
    depends_on:
      - mongo

networks:
  proxynet:
    name: "spark-mongo-net"
